/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Belen
 */
public class RedesSociales extends javax.swing.JFrame {

    /**
     * Creates new form RedesSociales
     */
    public RedesSociales() {
        initComponents();
        setTitle("Redes Sociales");
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/73537678_2463897243868204_8414604552279425024_n (2).jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Whatsapp = new javax.swing.JButton();
        Instagram = new javax.swing.JButton();
        Faceboook = new javax.swing.JButton();
        Youtube = new javax.swing.JButton();
        YoutubeJUNTADAS = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Whatsapp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Whatsapp.setText("IR");
        Whatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhatsappActionPerformed(evt);
            }
        });
        getContentPane().add(Whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        Instagram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Instagram.setText("IR");
        Instagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstagramActionPerformed(evt);
            }
        });
        getContentPane().add(Instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        Faceboook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Faceboook.setText("IR");
        Faceboook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaceboookActionPerformed(evt);
            }
        });
        getContentPane().add(Faceboook, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        Youtube.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Youtube.setText("IR");
        Youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YoutubeActionPerformed(evt);
            }
        });
        getContentPane().add(Youtube, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        YoutubeJUNTADAS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        YoutubeJUNTADAS.setText("IR");
        YoutubeJUNTADAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YoutubeJUNTADASActionPerformed(evt);
            }
        });
        getContentPane().add(YoutubeJUNTADAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        SALIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Youtube Juntadas:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Redes Sociales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Whatsapp:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Instagram:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Facebook:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Youtube");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/maravillloooooosoooo.gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 100));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/hurl1.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void WhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhatsappActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://chat.whatsapp.com/08fMwHhZIJPAsUbHG4c7Ud"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR,no se puede ejecutar el mensaje");
        }
    }//GEN-LAST:event_WhatsappActionPerformed

    private void InstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstagramActionPerformed
         try {
            Desktop.getDesktop().browse(new URI("https://instagram.com/incursioneshurlingham"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR,no se puede ejecutar el mensaje");
        }
    }//GEN-LAST:event_InstagramActionPerformed

    private void FaceboookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaceboookActionPerformed
         try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/groups/120983805238041"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR,no se puede ejecutar el mensaje");
        }
    }//GEN-LAST:event_FaceboookActionPerformed

    private void YoutubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YoutubeActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/channel/UCRoivzovgpVjGtaFUOI-glw"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR,no se puede ejecutar el mensaje");
        }
    }//GEN-LAST:event_YoutubeActionPerformed

    private void YoutubeJUNTADASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YoutubeJUNTADASActionPerformed
         try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/channel/UCLeyo8rDyUN-hdl_TdlGZZw"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR,no se puede ejecutar el mensaje");
        }
    }//GEN-LAST:event_YoutubeJUNTADASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedesSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedesSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedesSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedesSociales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedesSociales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton Faceboook;
    private javax.swing.JButton Instagram;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton Whatsapp;
    private javax.swing.JButton Youtube;
    private javax.swing.JButton YoutubeJUNTADAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
